Mitschriften aus ABWL
importPI19fromDHGE/dhge-pi19-sem4 pull request #10
Opened 2021-04-07 11:40 UTC by Steve2955

Hier die Mitschriften aus den vergangenen zwei LV. Da kann man bestimmt noch etwas ergänzen. Wenn jemand speziell was zu den Liniensystemen hat, gerne her damit.

2021-04-07 11:40 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- ABWL-LEDER/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-04-08 06:13 UTC, RvNovae approved these changes
Größtenteils typos und Kleinigkeiten, ansonsten danke ich :)

2021-04-08 06:13 UTC, RvNovae commented on ABWL-LEDER/README.md
> +- Beschäftigung: Sicherung von AP
Bei einigen der Abkürzungen wär ich mir an der Stelle nicht sicher, was die bedeuten. Vielleicht lieber ausschreiben?

2021-04-08 06:13 UTC, RvNovae commented on ABWL-LEDER/README.md
> +	- Anforderungen: fachlich, methodisch, persönlich Kenntnisse
```suggestion
	- Anforderungen: fachliche, methodische, persönliche Kenntnisse
```

2021-04-08 06:13 UTC, RvNovae commented on ABWL-LEDER/README.md
> +- Stellen mit gleicher Befugniss = Hierarchieebene
```suggestion
- Stellen mit gleicher Befugnis = Hierarchieebene
```

2021-04-08 06:13 UTC, RvNovae commented on ABWL-LEDER/README.md
> +  - Führung und Entscheidung vor Ort $\rightarrow$ hohe Akzeptanz; langsame Entscheidungsfindung; Notwendigkeit auonomer Gruppen
```suggestion
  - Führung und Entscheidung vor Ort $\rightarrow$ hohe Akzeptanz; langsame Entscheidungsfindung; Notwendigkeit autonomer Gruppen
```

2021-04-08 06:13 UTC, RvNovae commented on ABWL-LEDER/README.md
> +- Anforderungsprofil: Fachlich, Methodisch, Persönlich
```suggestion
- Anforderungsprofil: fachlich, methodisch, persönlich
```

2021-04-08 06:13 UTC, RvNovae commented on ABWL-LEDER/README.md
> +- **taktisch:** > 1 bis 5 Jahre; Mittelfristig, Teilziele (Ausbildung)
```suggestion
- **taktisch:** > 1 bis 5 Jahre; mittelfristig, Teilziele (Ausbildung)
```

2021-04-08 06:13 UTC, RvNovae commented on ABWL-LEDER/README.md
> +- **Vergangenheitsorientiert:** Trendexploration
```suggestion
- **vergangenheitsorientiert:** Trendexploration
```

2021-04-08 10:06 UTC, Steve2955 commented on ABWL-LEDER/README.md
> +- Beschäftigung: Sicherung von AP
Danke für alle Korrekturen. Die Abkürzungen habe ich jetzt ausgeschrieben.

2021-04-09 13:10 UTC, ZeroPointMax requested changes
Ich würde gerne kleinere Dinge ändern, ansonsten vielen vielen Dank für die Mitschriften...

2021-04-09 13:10 UTC, ZeroPointMax commented on ABWL-LEDER/README.md
> +- Beschäftigung: Sicherung von Arbeitsplätzen
```suggestion
- Beschäftigung: Sicherung von Arbeitsplätzen, inkl. Arbeitsmoral
```

2021-04-09 14:20 UTC, Steve2955 commented
@ZeroPointMax Danke für die Anmerkungen, sind übernommen 👍

2021-04-09 15:09 UTC, ZeroPointMax approved these changes
👍

2021-04-09 15:09 UTC, merged