Abwl sthinbetween 05112021
importPI19fromDHGE/dhge-pi19-sem4 pull request #124
Opened 2021-11-05 15:06 UTC by sthinbetween

Habe mich für die Prüfungsvorbereitung entschieden, die ganzen Mitschriften zu überarbeiten und ggf. zu ergänzen. Daher einiges an Änderungsvorschlagen und Ergänzungen für ABWL aus dem vergangenen Semester. Den Pull-Request heute schonmal. Ich würde aber bis Sonntag da noch reincommitten. Plane zumindest dieses WE damit fertig zu werden. So könnt ihr aber schonmal drüberschauen, wenn ihr Lust habt.

2021-11-05 17:31 UTC, ZeroPointMax commented
ACH DU KACKE

2021-11-05 17:37 UTC, sthinbetween commented
> ACH DU KACKE

Ja wat denn? ;)

2021-11-06 09:59 UTC, nukerxy commented
schaut mal hier rein, coordinate and collaborate https://github.com/Steve2955/dhge-pi19-sem5/commits/abwl-lkf/ABWL-LEDER
Mal absprechen, was bleibt
@Steve2955 @RvNovae

2021-11-06 10:02 UTC, sthinbetween commented
> 
> 
> schaut mal hier rein, coordinate and collaborate https://github.com/Steve2955/dhge-pi19-sem5/commits/abwl-lkf/ABWL-LEDER Mal absprechen, was bleibt @Steve2955 @RvNovae

wdym? Könntest du die Anforderung noch ein wenig ausfomrulieren, da es sich ja um das andere VL-Semester handelt?

2021-11-06 10:50 UTC, nukerxy commented
@sthinbetween Ich habe selbst keinen Überblick bisher, nur hat yannis schon lkf erstellt, Oliver fängt damit an und du hast jetzt auch sehr viel gemacht. Ich möchte gern, dass niemand seine Zeit verschwendet und irgendwas doppelt erstellt wird :)
alles gut!

2021-11-06 12:07 UTC, RvNovae commented
Die Sachen aus meinem PR könnte man eigentlich auch in ein LKF Dokument überführen, sind gestern eigentlich größtenteils nur so Kontrollfragen gewesen.

2021-11-06 12:07 UTC, sthinbetween commented
> 
> 
> Die Sachen aus meinem PR könnte man eigentlich auch in ein LKF Dokument überführen, sind gestern eigentlich größtenteils nur so Kontrollfragen gewesen.

@RvNovae Zu faul zum Suchen: Was kürzt ihr mit LKF ab?

2021-11-06 12:08 UTC, RvNovae commented
> 
> 
> > Die Sachen aus meinem PR könnte man eigentlich auch in ein LKF Dokument überführen, sind gestern eigentlich größtenteils nur so Kontrollfragen gewesen.
> 
> @RvNovae Zu faul zum Suchen: Was kürzt ihr mit LKF ab?

Lernkontrollfragen

2021-11-06 12:12 UTC, sthinbetween commented
Habe die LKF jetzt als eigenes Kapitel zum Abschluss des Organisationsteil. Sind bisher auch nur die Fragen, nicht die Antworten oder Verlinkungen auf die Themen. Mir ists egal ob wir das zentralisieren oder als Abschluss für die Hauptkapitel lassen.

2021-11-06 13:39 UTC, nukerxy requested changes
Danke für die Ausarbeitung!
LKF werden ausgelagert [LKF Sem 4](https://github.com/importPI19fromDHGE/dhge-pi19-sem4/blob/main/ABWL-LEDER/appendix/LKF.md) / Befüllen übernehmen wir dann; ggf existieren irgendwo schon Antworten.
Ich übernehme das, bis dahin wird mal geblockt.

2021-11-06 15:13 UTC, nukerxy commented on ABWL-LEDER/README.md
> +- Sie können Vor- und Nachteile aus den Strukturen ableiten
```suggestion

```

2021-11-08 15:27 UTC, sthinbetween commented
Jemand ne Ahnung, was pandoc von mir will? :D

2021-11-08 15:47 UTC, Steve2955 commented
> Jemand ne Ahnung, was pandoc von mir will? :D @ZeroPointMax @nukerxy
> 
> Ebenso: können gern erstmal mergen, da der erste Hauptteil ja abgeschlossen ist. Ich mach dann neues PR auf wenn ich wieder dran sitze

Über `pandoc` erstmal keine Sorgen machen. Da ist allgemein irgendwas kaputt gegangen.

2021-11-08 17:21 UTC, nukerxy approved these changes

2021-11-09 22:06 UTC, RvNovae approved these changes
Puh, da hast du dir aber echt eine ganz schöne Mühe gemacht 😅
Danke!

2021-11-09 22:09 UTC, RvNovae reviewed
Das *sollte* pandoc besänftigen, glaube ich 😁

2021-11-09 22:09 UTC, RvNovae commented on ABWL-LEDER/README.md
> +> Eine Übersicht zu Aufgabenanalyse und -synthese findet sich unter <http://www.bwl-betriebswirtschaft.de/gfx/aufbauorganisation-eines-unternehmens.jpg>
```suggestion
> Eine Übersicht zu Aufgabenanalyse und -synthese findet sich unter
![Übersicht zu Aufgabenanalyse und -synthese](http://www.bwl-betriebswirtschaft.de/gfx/aufbauorganisation-eines-unternehmens.jpg)<!--width=200px-->
```

2021-11-10 06:15 UTC, sthinbetween commented
> 
> 
> Das _sollte_ pandoc besänftigen, glaube ich 😁

@RvNovae leider nicht :(

2021-11-10 17:43 UTC, RvNovae commented
@sthinbetween kann ich #123 mergen oder sollte ich damit lieber noch warten?

2021-11-10 17:47 UTC, RvNovae reviewed
Verstehe den pandoc Fehler nicht so wirklich ... irgendwie versucht der da ein `shtml` file zu rendern? 🤔

2021-11-10 17:47 UTC, RvNovae commented on ABWL-LEDER/README.md
> +![Übersicht zu Aufgabenanalyse und -synthese](http://www.bwl-betriebswirtschaft.de/gfx/aufbauorganisation-eines-unternehmens.jpg)<!--width=200px-->
```suggestion
<http://www.bwl-betriebswirtschaft.de/gfx/aufbauorganisation-eines-unternehmens.jpg>
```

Dann würd ich das hier zumindest wieder zurück ändern, das war wahrscheinlich Quatsch meinerseits.

2021-11-14 10:40 UTC, sthinbetween commented on ABWL-LEDER/README.md
> +![Übersicht zu Aufgabenanalyse und -synthese](http://www.bwl-betriebswirtschaft.de/gfx/aufbauorganisation-eines-unternehmens.jpg)<!--width=200px-->
Habs. Es war ein von extern eingebundenes Bild, dass er nicht mochte. Habs rausgenommen. Jetzt würde ich mal mergen

2021-11-14 10:40 UTC, merged