SWS vom 19.04.2021
importPI19fromDHGE/dhge-pi19-sem4 pull request #18
Opened 2021-04-19 11:05 UTC by ZeroPointMax

Heute im Angebot*: Zertifikate, PGP, De-Mail, Bitcoin

* nur solange der vorrat reicht

2021-04-19 11:05 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- SWS-KUSCHE/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-04-19 14:50 UTC, Steve2955 requested changes
Danke für die Mitschriften @ZeroPointMax. Ich würde einige, aber meist nur kleine Änderungen vornehmen.

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +![GCM-Verschlüsselung](assets/gcm_encryption.png)<!--width=1080px-->
```suggestion
![GCM-Verschlüsselung](assets/gcm_encryption.png)<!--width=600px-->
```

Da das Bild im Hochformat ist, wird `width=1080px` hier glaube etwas arg groß.

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
>  - Nachteile
```suggestion
- Nachteile:
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
>  - Jeden Block separat verschlüsseln
```suggestion
- Datenstrom in Blöcke teilen $\rightarrow$ jeden Block separat verschlüsseln
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
>  - bei jedem Block vor Verschlüsselung wird XOR mit vorigem Chiffrat durchgeführt
```suggestion
- bei jedem Block wird vor der Verschlüsselung `XOR` mit vorherigem Chiffrat durchgeführt
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
>  - CA darf keine Kopie des Private Key haben
```suggestion
- Certificate Authority (CA) darf keine Kopie des Private Key haben
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +# PKI
```suggestion
## Public-Key-Infrastruktur
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +## Email-Verschlüsselung
```suggestion
# Anwendung: PGP, De-Mail

## Email-Verschlüsselung
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +  - d.h. überprüfbar, manipulatiossicher,...
```suggestion
  - d.h. überprüfbar, manipulationssicher,...
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- oft: richtiges Zertifikat? / Richtige Domain?
```suggestion
- oft: richtiges Zertifikat? / richtige Domain?
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +  - hierarchisches System - übergeordnete CA signiert untergeordnete
```suggestion
  - hierarchisches System $\rightarrow$ übergeordnete CA signiert untergeordnete
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- prüfen Korrektheit und Identität / Berechtigungen des Antragstellers
```suggestion
- Korrektheit und Identität prüfen (=Berechtigungen des Antragstellers)
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- stellt Zertifikat für Public Key aus, übermittelt Private Key geheim an Antragsteller (und löscht ihn dann hoffentlich)
```suggestion
- stellt Zertifikat für Public Key aus, übermittelt Private Key geheim an Antragsteller *(und löscht ihn dann hoffentlich)*
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- 2 Beziehungen zwischen Teilnehmern
```suggestion
- zwei Beziehungen zwischen Teilnehmern
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- z.B. für PGP
```suggestion
- nicht-hierarchische Alternative zu CAs (z.B. für PGP)
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +  - Gegenseitig ausgestellte Signaturen
```suggestion
  - enthalten Public Keys der Teilnehmer, gegenseitig ausgestellte Signaturen
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +
```suggestion
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- freie Implementierungen: OpenPGP und GPG
```suggestion
- durch RFC4880 standardisiert $\rightarrow$ freie Implementierungen: OpenPGP und GPG
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- sym. Schlüssel asym. verschlüsselt mit Elgamal
```suggestion
- sym. Schlüssel wird asym. mit Elgamal verschlüsselt 
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +## Probleme von PGP
```suggestion
### Probleme von PGP
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- wer garantiert die Authentizität
```suggestion
- Authentizität: Wer garantiert die Zuordnung zwischen Schlüsseln und Personen?
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +## Bitcoin
```suggestion
# Anwendung: Bitcoin (Blockchain)
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- ist ein Protokoll und den Implementierungen
```suggestion
- Blockchain-basierte Speicherung von Transaktionen zwischen Wallets
- P2P-Netzwerk, in dem Daten über Transaktionen und Blöcke in der Blockchain ausgetauscht werden
- Protokoll (Regelwerk) und dessen Implementierung
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- Absicherung des Wallets
```suggestion
- Absicherung der Wallets
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- jeder Block enthält kryptografischen Hash des **vorigen** Blocks, Zeitstempel, *beliebige Nutzdaten*
```suggestion
- jeder Block enthält kryptografischen Hash des **vorherigen** Blocks, Zeitstempel, *beliebige Nutzdaten* (= Transaktionen)
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- alle Blöcke vorher müssen erhalten bleiben, daher ist Bitcoin derzeit 200GB steigend groß
```suggestion
- alle Blöcke vorher müssen erhalten bleiben $\rightarrow$ Bitcoin-Blockchain derzeit 340GB (stetig wachsend)
- ```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- Verwendung für alles, was fälschungssicher protokolliert werden muss
```suggestion
- Verwendung für Alles, was fälschungssicher protokolliert werden muss (Prüfprotokolle, Lieferketten, Transaktionen, ...)
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- jeder Block enthält variaable Zusatzbits, die durch "Mining" bestimmt werden
```suggestion
- jeder Block enthält variable Zusatzbits (Nonce), die durch "Mining" bestimmt werden
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- d.h. langsam, verzögert, unzuverlässig
```suggestion
- asynchrone Kommunikation (d.h. langsam, verzögert, unzuverlässig)
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +### Konsensproblem
```suggestion
## Konsensproblem
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- Welcher neue Block wird unter den konkurrierenden akzeptiert?
```suggestion
- Wer darf anhängen? Welcher neue Block wird unter Konkurrierenden akzeptiert?
```

2021-04-19 14:50 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- System bricht zusammen, wenn ein Teilnehmer >50% der Rechenleistung kontrolliert
```suggestion
- Manipulationssicherheit des System bricht zusammen, wenn ein Teilnehmer >50% der Rechenleistung kontrolliert
```

2021-04-19 19:14 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +![CTR-Verschlüsselung](assets/ctr_encryption.png)<!--width=601px-->
ja, das ist die Originalbreite

2021-04-19 19:17 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +- prüfen Korrektheit und Identität / Berechtigungen des Antragstellers
Oh, das ist nicht dasselbe, vor allem im Kontext von Web-Zertifikaten.

2021-04-19 19:18 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +- prüfen Korrektheit und Identität / Berechtigungen des Antragstellers
```suggestion
- prüfen Korrektheit, Identität und Berechtigungen des Antragstellers
```

2021-04-19 19:22 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +- ist ein Protokoll und den Implementierungen
Find ich gut, mit Ausnahme der letzten Zeile. Ich meine, es gibt ein Regelwerk außerhalb des Protokolls. Also gibt es ein Bitcoin-Protokoll und eine Konfiguration davon

2021-04-19 19:23 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +- jeder Block enthält kryptografischen Hash des **vorigen** Blocks, Zeitstempel, *beliebige Nutzdaten*
Was meinst du mit Transaktionen?

Die Nutzdaten müssen keine Transaktion sein

2021-04-19 19:24 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +- alle Blöcke vorher müssen erhalten bleiben, daher ist Bitcoin derzeit 200GB steigend groß
Oha, da hast du Kusches Zahl sogar überboten :D

Hab mir in der VL schon gedacht: Da braucht man ja bald ne extra Platte für...

2021-04-20 07:11 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- jeder Block enthält kryptografischen Hash des **vorigen** Blocks, Zeitstempel, *beliebige Nutzdaten*
Stimmt schon, das ist hier wieder etwas durcheinander, in einigen Stichpunkten geht es um Blockchain allgemein und in anderen dann über den Einsatz in Bitcoin

2021-04-20 07:13 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- ist ein Protokoll und den Implementierungen
```suggestion
- Blockchain-basierte Speicherung von Transaktionen zwischen Wallets
- P2P-Netzwerk, in dem Daten über Transaktionen und Blöcke in der Blockchain ausgetauscht werden
- Bitcoin-Regelwerk: Protokoll und dessen Implementierung
```

2021-04-20 07:15 UTC, Steve2955 requested changes

2021-04-20 07:15 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- ```
```suggestion
```

2021-04-20 07:15 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- alle Blöcke vorher müssen erhalten bleiben \rightarrow\rightarrow Bitcoin-Blockchain derzeit 340GB (stetig wachsend)
```suggestion
- alle Blöcke vorher müssen erhalten bleiben $\rightarrow$ Bitcoin-Blockchain derzeit 340GB (stetig wachsend)
```

2021-04-20 07:47 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +- jeder Block enthält kryptografischen Hash des **vorigen** Blocks, Zeitstempel, *beliebige Nutzdaten*
Ich mein, selbst in Bitcoin muss das keine Transaktion sein, lt Herr Kusche

2021-04-20 07:47 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +- ```
Huch, was ist denn hier passiert?

2021-04-20 19:58 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- SWS-KUSCHE/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-04-20 19:59 UTC, ZeroPointMax commented
Da die Review bei den hochfrequenten LVS hier noch nicht beackert ist, füge ich den Kram von heute einfach hinzu :)

2021-04-21 10:28 UTC, Steve2955 approved these changes

2021-04-21 10:28 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- im einfachsten Fall Physische Inputs auf Qualität prüfen und zusammenhängen $\rightarrow$ Kryptographische Hashfunktion
```suggestion
- im einfachsten Fall physische Inputs auf Qualität prüfen und zusammenhängen $\rightarrow$ Kryptographische Hashfunktion
```

2021-04-21 10:28 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- versehentlicher Implementierungsfehler in OpenSSL in Debian, damit nur 2^15 <!--TODO: wie mache ich Potenzen in MathJax?-->Zufallszahlen
```suggestion
- versehentlicher Implementierungsfehler in OpenSSL in Debian, damit nur $2^{15}$ Zufallszahlen
```

Funktioniert genau so, wie man das erwarten würde, nur wenn du mehr als zwei Zeichen im Exponenten willst, musst du eine Klammer `{}` setzen^^

2021-04-21 10:28 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- Gefahr: selbes Passwort für viele Dienste verwendet $\rightarrow$ kein technisches Problem; Dienstanweisung etc. helfen evtl.
```suggestion
- Gefahr: selbes Passwort wird für viele Dienste verwendet $\rightarrow$ kein technisches Problem; Dienstanweisung etc. helfen evtl.
```

2021-04-21 10:28 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- Für Hochsicherheit: Passwörter nur aus Generator erlauben, müssen gut merkbar sein (aus Silben besthend, lange Phrasen), Auswahl aus mehreren Vorschlägen, nach außen hin unbekannte Generator-Logik
```suggestion
- Für Hochsicherheit: Passwörter nur aus Generator erlauben, müssen gut merkbar sein (aus Silben bestehend, lange Phrasen), Auswahl aus mehreren Vorschlägen, nach außen hin unbekannte Generator-Logik
```

2021-04-21 10:28 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- kein 100%iger Schutz möglich
```suggestion
- kein 100%iger Schutz möglich (besonders in VMs)
```
Weiß nicht, ob man das hier noch ergänzen sollte, kannst du aber gerne auch ignorieren

2021-04-21 11:04 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +- versehentlicher Implementierungsfehler in OpenSSL in Debian, damit nur 2^15 <!--TODO: wie mache ich Potenzen in MathJax?-->Zufallszahlen
uhh danke ^^

2021-04-22 06:39 UTC, Steve2955 requested changes

2021-04-22 06:39 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- im einfachsten Fall physische Inputs auf Qualität prüfen und zusammenhängen \rightarrow\rightarrow Kryptographische Hashfunktion
```suggestion
- im einfachsten Fall physische Inputs auf Qualität prüfen und zusammenhängen $\rightarrow$ Kryptographische Hashfunktion
```

Das `\rightarrow\rightarrow` hast du nicht gezielt geändert, oder? Den Fehler habe ich irgendwo schonmal korrigiert 🤔

2021-04-22 06:39 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- Gefahr: selbes Passwort wird für viele Dienste verwendet \rightarrow\rightarrow kein technisches Problem; Dienstanweisung etc. helfen evtl.
```suggestion
- Gefahr: selbes Passwort wird für viele Dienste verwendet $\rightarrow$ kein technisches Problem; Dienstanweisung etc. helfen evtl.
```

Ich habe offiziell keine Ahnung, was damit los ist 😅

2021-04-22 06:57 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +- Gefahr: selbes Passwort wird für viele Dienste verwendet \rightarrow\rightarrow kein technisches Problem; Dienstanweisung etc. helfen evtl.
Ich hab hier auch keine Ahnung, wo kommt das her??

Ich mach im VScode immer ``$\rightarrow$``, das muss irgendwie von einem Programm geändert werden

2021-04-22 07:01 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +- Gefahr: selbes Passwort wird für viele Dienste verwendet \rightarrow\rightarrow kein technisches Problem; Dienstanweisung etc. helfen evtl.
Tatsache, die werden mir im VScode schon so dargestellt. Der parst das also zumindest nicht transparent beim Schreiben um...

2021-04-22 07:21 UTC, Steve2955 approved these changes

2021-04-22 07:21 UTC, Steve2955 commented
@ZeroPointMax hast du auch Mitschriften zu der LV von Gestern gemacht?

2021-04-22 07:44 UTC, ZeroPointMax commented
@Steve2955 ja, kann ich auch hier rein mergen, wusste nicht, ob das so ne gute Idee wäre

2021-04-22 07:54 UTC, Steve2955 commented
@ZeroPointMax Kannst ja einfach eine PR auf diese Branch machen

2021-04-22 08:51 UTC, Steve2955 approved these changes
Next try 😅

2021-04-22 08:51 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- durch RFC4880 standardisiert \rightarrow\rightarrow freie Implementierungen: OpenPGP und GPG
```suggestion
- durch RFC4880 standardisiert $\rightarrow$ freie Implementierungen: OpenPGP und GPG
```

2021-04-22 08:51 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- Datenstrom in Blöcke teilen \rightarrow\rightarrow jeden Block separat verschlüsseln
```suggestion
- Datenstrom in Blöcke teilen $\rightarrow$ jeden Block separat verschlüsseln
```

2021-04-22 08:51 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +  - hierarchisches System \rightarrow\rightarrow übergeordnete CA signiert untergeordnete
```suggestion
  - hierarchisches System $\rightarrow$ übergeordnete CA signiert untergeordnete
```

2021-04-22 08:54 UTC, Steve2955 approved these changes
Success? 😂

2021-04-22 15:35 UTC, nukerxy approved these changes

2021-04-23 15:50 UTC, merged