SWS vom 26.04.21
importPI19fromDHGE/dhge-pi19-sem4 pull request #26
Opened 2021-04-26 19:44 UTC by ZeroPointMax

2021-04-26 19:44 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- SWS-KUSCHE/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-04-26 19:44 UTC, ZeroPointMax commented
Ups, bei mir ist noch nicht ganz drin, dass ich ``-S`` beim Committen machen muss

2021-04-26 20:54 UTC, Steve2955 approved these changes
Danke für die Mitschriften 👍

2021-04-26 20:54 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +  - Lösung: "Einmal-IDs": selber Request mit selber Session wird nur einmal akzeptiert (Schutz gegen Replay-Attacken)#
```suggestion
  - Lösung: "Einmal-IDs": selber Request mit selber Session wird nur einmal akzeptiert (Schutz gegen Replay-Attacken)
```

2021-04-26 20:54 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +  - **Daten vom Client sind nie vertrauenswürdig**; alle sicherheitsrelevanten Prüfungen müssen am Server stattfinden
```suggestion
  - **Daten vom Client sind nie vertrauenswürdig** $\rightarrow$ alle sicherheitsrelevanten Prüfungen müssen am Server stattfinden
```

2021-04-26 20:54 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +  - Variante 2: getrennte Prozesse; einer mit erhöhten Rechten (so wenig wie möglich Code) und einer mit normalen Rechten (Großteil des Codes)
```suggestion
  - Variante 2: getrennte Prozesse; einer mit erhöhten Rechten (so wenig Code wie möglich) und einer mit normalen Rechten (Großteil des Codes)
```

2021-04-26 20:54 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- Szenario: Server will temp. File anlegen - Angreifer legt Link der Zieldatei auf ``/etc/passwd``, Server überschreibt diese Datei
```suggestion
- Szenario: Server will temp. File anlegen, Angreifer legt Link der Zieldatei auf `/etc/passwd` $\rightarrow$ Server überschreibt diese Datei
```

2021-04-26 20:54 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +  - des Inhaltes
```suggestion
- automatische Updates ohne Absicherung der Verbindung und des Inhaltes
```

2021-04-26 20:54 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- Was filtert man? Z.B. SQL-Injections, JavaScript, HTML, alle Shell-Aufrufe (Klassiker: Mailadressen), ...
```suggestion
- Was filtert man? z.B. SQL-Injections, JavaScript, HTML, alle Shell-Aufrufe (Klassiker: Mailadressen), ...
```

2021-04-26 20:54 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +### LDAP-Inection
```suggestion
### LDAP-Injection
```

2021-04-26 20:54 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- Problem 4: die zukünftigen Features einer Shell sind fast unüberschaubar; Filterung könnte zukünftig nicht mehr reichen
```suggestion
- Problem 4: die zukünftigen Features einer Shell sind fast unüberschaubar $\rightarrow$ Filterung könnte zukünftig nicht mehr reichen
```

2021-04-26 20:54 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +### XSS - Cross Site Scripting
```suggestion
### Cross Site Scripting (XSS)
```

2021-04-26 20:54 UTC, Steve2955 commented on SWS-KUSCHE/README.md
> +- Nutzung von Zeihenklassen-Prüffunktionen (`isalpha`, `isdigit`, ...)
```suggestion
- Nutzung von Zeichenklassen-Prüffunktionen (`isalpha`, `isdigit`, ...)
```

2021-04-26 21:48 UTC, nukerxy requested changes

2021-04-26 21:48 UTC, nukerxy commented on SWS-KUSCHE/README.md
> +  - "Rule of Ten": jeder Fehler kostet das Zehnfache von dem, was es gekostet hätte, ihn von Anfang an zu vermeiden
```suggestion
  - "Rule of Ten": Die Fehlerkosten eines nicht entdeckten Fehlers erhöhen sich von Stufe zu Stufe der Wertschöpfung/Entwicklung um den Faktor 10
```

2021-04-26 21:48 UTC, nukerxy commented on SWS-KUSCHE/README.md
> +- Kategorien: SQL-Injection, Command Injection, Cross Site Scripting, Directory Traversal, Format String Exploits (z.B. ``printf``: formatiert Strings, interpretiert `%`), Regular Exressions (nutzen
```suggestion
- Kategorien: SQL-Injection, Command Injection, Cross Site Scripting, Directory Traversal, Format String Exploits (z.B. ``printf``: formatiert Strings, interpretiert `%`), Regular Expressions (nutzen JIT-Compiler; erlauben Rekursion)
```

2021-04-27 07:52 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +  - Lösung: "Einmal-IDs": selber Request mit selber Session wird nur einmal akzeptiert (Schutz gegen Replay-Attacken)#
#####

2021-04-27 07:52 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +  - Lösung: "Einmal-IDs": selber Request mit selber Session wird nur einmal akzeptiert (Schutz gegen Replay-Attacken)#
hahaha, der hat die ##### weggeparst

2021-04-27 07:54 UTC, ZeroPointMax commented on SWS-KUSCHE/README.md
> +- Was filtert man? Z.B. SQL-Injections, JavaScript, HTML, alle Shell-Aufrufe (Klassiker: Mailadressen), ...
Technisch gesehen falsch, weil das Fragezeichen ein Satzende signalisiert und daher das nächste Zeichen groß sein muss :P

2021-04-27 07:56 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- SWS-KUSCHE/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-04-27 08:46 UTC, nukerxy approved these changes

2021-04-27 08:46 UTC, merged