Embedded Systems: Mitschriften 27.04.2019
importPI19fromDHGE/dhge-pi19-sem4 pull request #27
Opened 2021-04-27 11:48 UTC by Steve2955

Timer/Zähler

2021-04-27 11:48 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- EMB-GUENTHER/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-04-27 19:07 UTC, ZeroPointMax requested changes
Sieht soweit gut aus, aber wie inline angemerkt, wird das MathJax nicht richtig gerendert.

Zudem hab ich ne Verständnisfrage, aber die Beantwortung davon sehe ich mal als optional an.

2021-04-27 19:07 UTC, ZeroPointMax commented on EMB-GUENTHER/README.md
> +- je nach Konfiguration kann der Zähler der Interrupt ausgelöst werden (= interne Interrupt-Quelle)
Also kann ein Zähler einen Interrupt auslösen?

Genau einen oder wie läuft das ab?

2021-04-27 19:07 UTC, ZeroPointMax commented on EMB-GUENTHER/README.md
> +> $$\text{OCRn} = [\frac{16\text{MHz}}{64}*1*10^{-3}s]-1=\underline{\underline{249}}$$
während mein Chrome das hier in der PR-Ansicht rendert, dafür das darüber nicht, ist es genau umgekehrt, wenn man sich die Branch normal anguckt. Sprich das hier wird nicht gerendert.

2021-04-27 19:13 UTC, Steve2955 commented on EMB-GUENTHER/README.md
> +- je nach Konfiguration kann der Zähler der Interrupt ausgelöst werden (= interne Interrupt-Quelle)
Ja, ein Zähler kann einen Interrupt auslösen. Jeder Zähler hat dazu eine Maske (= Bedingung für den Interrupt) wenn die erreicht ist, wird die Programmausführung pausiert und in die ISR gesprungen. Für die drei Zähler im Arduino könntest du also drei verschiedene Masken (Zeiten) mit jeweils anderen ISRs definieren.

2021-04-27 19:15 UTC, Steve2955 commented on EMB-GUENTHER/README.md
> +> $$\text{OCRn} = [\frac{16\text{MHz}}{64}*1*10^{-3}s]-1=\underline{\underline{249}}$$
Du hast recht, sehr komisch. Ich würde die zweite Formel einfach aus der Quote rausnehmen 😅

2021-04-27 19:19 UTC, ZeroPointMax commented on EMB-GUENTHER/README.md
> +- je nach Konfiguration kann der Zähler der Interrupt ausgelöst werden (= interne Interrupt-Quelle)
Aha, verstehe. Jetzt verstehe ich auch den Kommentar in der Prüfungsfrage ^^

2021-04-27 19:19 UTC, Steve2955 commented on EMB-GUENTHER/README.md
> +- je nach Konfiguration kann der Zähler der Interrupt ausgelöst werden (= interne Interrupt-Quelle)
@ZeroPointMax Hat nicht funktioniert. Ich kann es mir offiziell nicht erklären 😅

2021-04-27 19:21 UTC, ZeroPointMax commented
![image](https://user-images.githubusercontent.com/26359277/116299836-771d1c80-a79e-11eb-890d-f06e779554ab.png)

ja, also irgendwas haut hier nicht hin xD 

oder mein Chrome spinnt

2021-04-27 19:22 UTC, ZeroPointMax commented
Vielleicht wissen ja @RvNovae oder @photovoltex, was hier schiefläuft? Ist doch so ein bisschen LaTeX oder?

2021-04-27 20:07 UTC, RvNovae commented
Also ich kenne es so, dass Variablen kursiv geschrieben werden. Deshalb sollte man sie ohne `\text{}` schreiben.
Einheiten widerrum schreibt man mit `\mathrm{}`. Was im Script steht rendered mir vscode aber korrekt. 
Scheint also an der chrome extension zu liegen. 

Zeile 211 würde ich persönlich so schreiben:
```tex
$$OCRn = [\frac{16\mathrm{MHz}}{64}*1*10^{-3}\mathrm{s}]-1=\underline{\underline{249}}$$
```

2021-04-28 07:41 UTC, ZeroPointMax commented
Hat es leider [nicht repariert](https://github.com/ZeroPointMax/dhge-pi19-sem4/blob/EMB-YANNIS-210427/EMB-GUENTHER/README.md#timer-z%C3%A4hler) :/

Wobei es in meinem VSCode auch richtig gerendert wird. Scheint, als hätten wir das Plugin zerschossen

2021-04-28 08:02 UTC, ZeroPointMax commented
![image](https://user-images.githubusercontent.com/26359277/116368624-d283f480-a808-11eb-9b7c-a1f19e1e3132.png)

*vielleicht* related, man weiß es nicht

2021-04-28 15:34 UTC, Steve2955 commented
@ZeroPointMax Schieben wir es auf die Chrome-Erweiterung oder wollen wir hier noch was machen?

2021-04-28 16:37 UTC, ZeroPointMax approved these changes

2021-04-29 08:24 UTC, RvNovae approved these changes

2021-04-29 08:40 UTC, merged