Mitschriften Systementwicklung 19.05.2021
importPI19fromDHGE/dhge-pi19-sem4 pull request #49
Opened 2021-05-19 15:28 UTC by RvNovae

2021-05-19 15:28 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/appendix/praktikum.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- SWE-KASCHE/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-05-19 16:04 UTC, RvNovae commented on SWE-KASCHE/README.md
> +
```suggestion

```

2021-05-19 16:04 UTC, RvNovae commented on SWE-KASCHE/README.md
> +- **Fan-IN**: Anzahl an Stellen, wo der Kontrollfluss in das Modul hineingeht
```suggestion

- **Fan-IN**: Anzahl an Stellen, wo der Kontrollfluss in das Modul hineingeht
```

2021-05-19 16:04 UTC, RvNovae commented on SWE-KASCHE/README.md
> +- $Anzahl Getter Setter - Anzahl Attribute$ soll $= 0$ sein
```suggestion

- $Anzahl Getter Setter - Anzahl Attribute$ soll $= 0$ sein
```

2021-05-19 16:04 UTC, RvNovae commented on SWE-KASCHE/README.md
> +- skaliert auf Anzahl der Methoden und Attribute
```suggestion
- skaliert auf Anzahl der Methoden und Attribute

```

2021-05-19 17:08 UTC, nukerxy approved these changes

2021-05-19 17:08 UTC, nukerxy commented on SWE-KASCHE/README.md
> +## Metriken für den Software-Architekture-Entwurf
```suggestion
## Metriken für den Software-Architektur-Entwurf
```

2021-05-19 17:08 UTC, nukerxy commented on SWE-KASCHE/README.md
> +- $\copyright$ Corol / Glass 1990
```suggestion
- $\copyright$ Corol / Glass 1990

```

2021-05-19 17:08 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/appendix/praktikum.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- SWE-KASCHE/README.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-05-19 19:20 UTC, ZeroPointMax approved these changes
Danke, dass du das wieder übernommen hast, wir wissen dein Opfer zu schätzen

2021-05-19 19:20 UTC, ZeroPointMax commented on SWE-KASCHE/README.md
> +- hoher FAN-IN $\Rightarrow$ schwache Kohäsion
geht das klar, wenn rightarrow hier groß geschrieben wird?

2021-05-19 19:20 UTC, ZeroPointMax commented on SWE-KASCHE/README.md
> +**Maß für Kapselung** $\copyright$ PIA19 <!-- :^) -->
:^)

2021-05-19 19:20 UTC, ZeroPointMax commented on SWE-KASCHE/README.md
> +- Anzahl Getter Setter - Anzahl AttributeAnzahl Getter Setter - Anzahl Attribute soll $= 0$ sein
```suggestion
- Anzahl Getter + Setter - Anzahl Attribute soll $= 0$ sein
```

2021-05-19 19:20 UTC, ZeroPointMax commented on SWE-KASCHE/README.md
> +- Anzahl Getter Setter - Anzahl AttributeAnzahl Getter Setter - Anzahl Attribute soll $= 0$ sein
ist das so richtig?

2021-05-19 19:20 UTC, ZeroPointMax commented on SWE-KASCHE/README.md
> +<!-- der code ändert sich doch eh ständig, das ist doch nach 10 minuten komplett outdated ... naja -->
Ja... Muss ich mal meinem Dev-Kollegen zeigen, der amüsiert sich da vielleicht

2021-05-20 06:21 UTC, Steve2955 commented on SWE-KASCHE/README.md
> +- Anzahl Getter Setter - Anzahl AttributeAnzahl Getter Setter - Anzahl Attribute soll $= 0$ sein
Wir sind auf was Richtung `(Anzahl Attribute - Anzahl Setter) + (Anzahl Attribute - Anzahl Getter)` gekommen 😅

2021-05-20 06:23 UTC, RvNovae commented on SWE-KASCHE/README.md
> +- hoher FAN-IN $\Rightarrow$ schwache Kohäsion
$\rightarrow$ -> einzelner pfeil
$\Rightarrow$ ->doppelter pfeil

2021-05-20 06:23 UTC, RvNovae commented on SWE-KASCHE/README.md
> +- Anzahl Getter Setter - Anzahl AttributeAnzahl Getter Setter - Anzahl Attribute soll $= 0$ sein
Ich habs etwas abgekürzt

2021-05-20 06:23 UTC, RvNovae commented on SWE-KASCHE/README.md
> +<!-- der code ändert sich doch eh ständig, das ist doch nach 10 minuten komplett outdated ... naja -->
hehe

2021-05-20 06:26 UTC, Steve2955 requested changes
Wir sind mit Kasche noch ein paar Punkte weiter gekommen. Danke für die Mitschriften 👍

2021-05-20 06:26 UTC, Steve2955 commented on SWE-KASCHE/README.md
> +- Anzahl an Objekten, die von einer Klasse benutzt werden
```suggestion
- Anzahl an Objekten, die von einer Klasse benutzt werden
- Kaskadierende Änderungen können durch Anpassungen der Unterobjekte notwendig werden

**Response for a class (RFC)**

- Anzahl an Methoden, die durch eine Nachrichten-Objekt der Klasse aufgerufen werden können

**Depth of Inheritance-Tree (DIT)**

- Vererbungsbaum: Tiefe des Baumes

**Number of Subclasses (NOC)**

- Anzahl der Subclass-Kinder

```

2021-05-20 14:12 UTC, merged