ASM vom 26.05.21
importPI19fromDHGE/dhge-pi19-sem4 pull request #52
Opened 2021-05-26 19:25 UTC by ZeroPointMax

And another one

2021-05-26 19:25 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/appendix/praktikum.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- ASM-GUENTHER/appendix/praktikum.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-05-26 19:48 UTC, nukerxy approved these changes
linting -  vielleicht In andere Datei auslagern?

2021-05-27 11:23 UTC, ZeroPointMax commented
> linting - vielleicht In andere Datei auslagern?

wäre ein Ansatz, ich hab aber gesehen, dass der zum Glück nur harmlose Sachen ~~in einem FUCKING Codeblock!!!~~ lintet

2021-05-27 11:24 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/appendix/praktikum.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- ASM-GUENTHER/appendix/praktikum.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-05-27 11:35 UTC, ZeroPointMax commented
Ich füge heutige LVS an

2021-05-27 17:23 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/appendix/praktikum.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- ASM-GUENTHER/appendix/praktikum.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-05-27 18:30 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/appendix/praktikum.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- ASM-GUENTHER/appendix/praktikum.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-05-27 18:31 UTC, ZeroPointMax commented
@nukerxy kannst du dir die neuen Sachen bitte auch anschauen? :-)

2021-05-27 19:15 UTC, nukerxy commented on ASM-GUENTHER/appendix/praktikum.md
> +- Register<!--Kranplätze--> müssen gesichert<!--verdichtet--> sein und danach wiederhergestellt werden
🤣

2021-05-27 19:24 UTC, nukerxy approved these changes
Vielen Dank
Der Timer war bei mir persönlich einfach zu viel heute 🤕 , muss ich nochmal anschauen

2021-05-27 19:24 UTC, nukerxy commented on ASM-GUENTHER/appendix/praktikum.md
> +  - 2 Modi für PWM:
```suggestion
  - 2 Modi für Pulsweitenmodulation:
```

2021-05-27 19:29 UTC, Steve2955 requested changes
Kann es sein, dass die Bilder fehlen? Eventuell liegt es an der `.gitignore`?

2021-05-27 19:29 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +rjmp main
Eins von den `rjmp main` ist doch zu viel?

2021-05-27 19:29 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +***********************************/
Ich bin persönlich gar kein Fan, von diesen riesigen Kommentarblöcken. Wollen wir das wirklich so mit reinnehmen? 😅

2021-05-27 19:29 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +- erfordert initialisierten Stack (ist standardmäßig 0)
```suggestion
- erfordert initialisierten Stack (liegt standardmäßig auf Adresse 0)
```
Meinst du das so? Hab persönlich noch nicht ganz verstanden, warum die Stack-Initialisierung sonst gebraucht wird. Also wenn das so nicht stimmt, korrigiert mich gerne

2021-05-27 19:29 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +- Aktivierung über Register
```suggestion
- Aktivierung über `GICR`-Register, Konfiguration über `MCUCR`, `EMCUCR`-Register
```

2021-05-27 19:29 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +- INT2 wird in EMCUCR konfiguriert, wobei hier nur die Flanke eingestellt werden kann
```suggestion
- INT2 wird in EMCUCR konfiguriert, wobei hier nur die Impulsdauer eingestellt werden kann
```
![image](https://user-images.githubusercontent.com/21085384/119884719-3ea16780-bf31-11eb-9f06-5ea23a5f220f.png)

2021-05-27 19:29 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +- INT2 wird in EMCUCR konfiguriert, wobei hier nur die Flanke eingestellt werden kann
```suggestion
- General Interrupt Flag Register (`GIFR`): gesetzt bei entsprechendem Ereignis
- vom MC gelöscht
- General Interrupt Control Register (`GICR`): Wenn entsprechendes Bit gesetzt, ist ein Interrupt aktiviert
- Microcontroller-Unit-Control-Register (`MCUCR`): Konfiguriert, welche Konfiguration von `INT0` und `INT1` einen Interrupt auslöst und ob auf steigende oder fallende Flanken reagiert wird
- `INT2` wird in `EMCUCR` konfiguriert, wobei hier nur die Flanke eingestellt werden kann
```
Sry, ich mag es einfach die Befehle so zu formatieren, will es dir aber natürlich nicht aufzwingen 😂

2021-05-27 19:29 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +- rjmp zur ISR
```suggestion
- `rjmp` zur ISR
```

2021-05-27 19:32 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +- INT2 wird in EMCUCR konfiguriert, wobei hier nur die Flanke eingestellt werden kann
Wenn nicht, bitte einfach ignorieren. Hab das nicht aus der LV, sondern selbst gerade nur im Datasheet gelesen 😅

2021-05-27 20:11 UTC, RvNovae requested changes
Erstmal vielen Dank für die tollen Mitschriften!
Mir ists irgendwie schwer gefallen zuzuhören, das hier wird mir sehr helfen!

Habe allerdings noch ein paar Anmerkungen.

2021-05-27 20:11 UTC, RvNovae commented on ASM-GUENTHER/appendix/praktikum.md
> +  - wird abgearbeitet, bis ``reti`` ("REturn To Interrupt") erreicht
```suggestion
  - wird abgearbeitet, bis ``reti`` ("Return To Interrupt") erreicht
```

2021-05-27 20:11 UTC, RvNovae commented on ASM-GUENTHER/appendix/praktikum.md
> +- rjmp zur ISR
```suggestion
- ``rjmp`` zur ISR
```
Max macht ja immer doppelte

2021-05-27 20:11 UTC, RvNovae commented on ASM-GUENTHER/appendix/praktikum.md
> +- INT2 wird in EMCUCR konfiguriert, wobei hier nur die Flanke eingestellt werden kann
```suggestion
- General Interrupt Flag Register (``GIFR``): gesetzt bei entsprechendem Ereignis
- vom MC gelöscht
- General Interrupt Control Register (``GICR``): Wenn entsprechendes Bit gesetzt, ist ein Interrupt aktiviert
- Microcontroller-Unit-Control-Register (``MCUCR``): Konfiguriert, welche Konfiguration von ``INT0`` und ``INT1`` einen Interrupt auslöst und ob auf steigende oder fallende Flanken reagiert wird
- ``INT2`` wird in ``EMCUCR`` konfiguriert, wobei hier nur die Flanke eingestellt werden kann
```

2021-05-27 20:11 UTC, RvNovae commented on ASM-GUENTHER/appendix/praktikum.md
> +- Es gibt die Konstante ``RAMEND`` :-)
Die Nudelservice Idee find ich immer noch super

2021-05-27 20:11 UTC, RvNovae commented on ASM-GUENTHER/appendix/praktikum.md
> +ldi work, HIGH, RAMEND
```suggestion
ldi work, HIGH(RAMEND)
```

oder 🤔

2021-05-27 20:11 UTC, RvNovae commented on ASM-GUENTHER/appendix/praktikum.md
> +* Autor: Max KErst                 *
```suggestion
* Autor: Max Kerst                 *
```

2021-05-27 20:17 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +- rjmp zur ISR
Die paar Byte extra Speicherplatz für Doppelte sind denke noch drin😂 

Aber ich bleibe bei meinen Einfachen, läuft wieder auf persönlich Präferenzen raus 😅

2021-05-27 20:18 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +ldi work, HIGH, RAMEND
Stimmt, ist mir gar nicht aufgefallen 😅

2021-05-27 20:18 UTC, RvNovae commented on ASM-GUENTHER/appendix/praktikum.md
> +- rjmp zur ISR
Ah jo sicher, ich persönlich mach auch lieber einfache. 
Meinte nur vonwegen "Konsistenz innerhalb der Datei" oder so aber meinetwegen können wirs auch mischen. Ist mir eigentlich relativ egal 😄

2021-05-28 09:10 UTC, ZeroPointMax commented on ASM-GUENTHER/appendix/praktikum.md
> +***********************************/
Hmm die blähen schon etwas auf, ja

2021-05-28 09:13 UTC, ZeroPointMax commented on ASM-GUENTHER/appendix/praktikum.md
> +* Autor: Max KErst                 *
meh, die mache ich mal weg, wie von @Steve2955 vorgeschlagen. Aber nice catch; ich bleibe gerne mal auf SHift hängen ;)

2021-05-28 09:17 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/appendix/praktikum.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- ASM-GUENTHER/appendix/praktikum.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-05-28 09:23 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/appendix/praktikum.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- ASM-GUENTHER/appendix/praktikum.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-05-28 09:24 UTC, ZeroPointMax commented
So, jetzt sollte alles umgesetzt sein

2021-05-28 09:28 UTC, ZeroPointMax commented on ASM-GUENTHER/appendix/praktikum.md
> +  - wird abgearbeitet, bis ``reti`` ("REturn To Interrupt") erreicht
Oh, das war tatsächlich Absicht, macht aber nix

2021-05-28 09:30 UTC, merged