ASM vom 28.05.21
importPI19fromDHGE/dhge-pi19-sem4 pull request #53
Opened 2021-05-28 16:57 UTC by ZeroPointMax

Leider kam ich diesmal nicht ganz so flüssig durch - Ergänzungen sind sehr willkommen :-)

2021-05-28 16:58 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/appendix/praktikum.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- ASM-GUENTHER/appendix/praktikum.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-05-28 16:59 UTC, Steve2955 commented
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>Run doctoc</em></summary>

```Shell
changed:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/appendix/praktikum.md
unchanged:
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ABWL-LEDER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/ASM-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/DBS-DORENDORF/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/PRO-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWE-KASCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/SWS-KUSCHE/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/EMB-GUENTHER/README.md
  - /home/runner/work/dhge-pi19-sem4/dhge-pi19-sem4/OOP-CASSELT/README.md
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- ASM-GUENTHER/appendix/praktikum.md

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/toc-generator) | [:memo: Issues](https://github.com/technote-space/toc-generator/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/toc-generator)

2021-05-28 17:15 UTC, RvNovae requested changes

2021-05-28 17:15 UTC, RvNovae commented on ASM-GUENTHER/appendix/praktikum.md
> +- Syntax: ``.db daten, Zeilenumbruch, Carriage Return, Terminator`` $\rightarrow$ ``.db "ganz erstaunlich!, 10, 13, 0"``
```suggestion
- Syntax: ``.db daten, Zeilenumbruch, Carriage Return, Terminator`` $\rightarrow$ ``.db "ganz erstaunlich!", 10, 13, 0``
```
Kam bei ihm das doppelte Anführungszeichen nicht am Ende vom String? 🤔

2021-05-28 17:15 UTC, RvNovae commented on ASM-GUENTHER/appendix/praktikum.md
> +  .db "Hier stehen Daten!",10,13,0
^ hier ist das ja auch so

2021-05-28 17:15 UTC, RvNovae commented on ASM-GUENTHER/appendix/praktikum.md
> +  - UBRR ist ein abwärtszähler; bei 0 wird ein Taktsignal generiert
```suggestion
  - UBRR ist ein Abwärtszähler; bei 0 wird ein Taktsignal generiert
```

2021-05-28 19:23 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +  - UBRR ist ein abwärtszähler; bei 0 wird ein Taktsignal generiert
```suggestion
  - ``UBRR`` ist ein Abwärtszähler; bei 0 wird ein Taktsignal generiert
```

2021-05-28 19:34 UTC, Steve2955 approved these changes
Danke für die Mitschriften 👍

2021-05-28 19:34 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +- Datenregister: UDR
```suggestion
- Datenregister: ``UDR``
```

2021-05-28 19:34 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +- Datenregister: UDR
```suggestion
- Konfiguration: mit Registern ``UCSRA``, ``UCSRB``, ``UCSRC``
  - ``UCSRC``-Register: ``UMSEL``-Bit: High = synchron
  - Double Speed Asynchronous Mode: ``U2X``-Bit in ``UCRSA``
  - Synchronisation Mater/Slave $\rightarrow$ DDR für Pin PD4 (``XCK``)
  - Baudrate in Register ``UBRR`` (High und Low)
- Datenregister: ``UDR``
```

2021-05-28 19:34 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +  - Beispiel asynchron: UBRR = (MC-Takt) / (16 * Zielbaudrate) - 1 <!--TODO: in MathJax umwandeln-->
```suggestion
  - Beispiel asynchron: $\text{UBRR} = \frac{\text{MC-Takt}}{16 * \text{Zielbaudrate}} - 1$
```
Wenn die `-1` hinter den Bruch kommst, sollte das so passen ^^

2021-05-28 19:34 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +  - Paritätseinstelllung
```suggestion
  - Paritätseinstellung
```

2021-05-28 19:34 UTC, Steve2955 commented on ASM-GUENTHER/appendix/praktikum.md
> +<!--ab hier hatte ich Filmriss-->
Ich kann hier gerne ansetzen, wenn wir nächste Woche die entsprechende LV bei Grimm haben

2021-05-30 09:00 UTC, ZeroPointMax commented on ASM-GUENTHER/appendix/praktikum.md
> +- Syntax: ``.db daten, Zeilenumbruch, Carriage Return, Terminator`` $\rightarrow$ ``.db "ganz erstaunlich!, 10, 13, 0"``
ups

2021-05-30 09:02 UTC, ZeroPointMax commented on ASM-GUENTHER/appendix/praktikum.md
> +<!--ab hier hatte ich Filmriss-->
Cool ^^

Machst du ne eigene Branch oder kommt das dann hier rein?

2021-05-30 10:59 UTC, RvNovae approved these changes

2021-05-30 14:45 UTC, ZeroPointMax commented on ASM-GUENTHER/appendix/praktikum.md
> +<!--ab hier hatte ich Filmriss-->
Ach, du kannst dann ja gerne eine separate PR machen, da kommt das hier schonmal in Upstream rein ^^

2021-05-30 14:45 UTC, merged