Neue Fragen und Teamsmeeting
importPI19fromDHGE/dhge-pi19-sem4 pull request #69
Opened 2021-06-02 09:32 UTC by nukerxy

Änderungen aus der Besprechung und die Fragen der letzten Beiden Lernzielkontrollen

2021-06-02 10:09 UTC, ZeroPointMax approved these changes

2021-06-02 10:09 UTC, ZeroPointMax commented on ASM-GUENTHER/README.md
> +- [C++ und Make](#c-und-make-1)
Hä?

2021-06-02 10:22 UTC, nukerxy commented on ASM-GUENTHER/README.md
> +- [C++ und Make](#c-und-make-1)
automatisch, frag mich bitte nicht

2021-06-02 10:33 UTC, nukerxy commented on ASM-GUENTHER/README.md
> +- [C++ und Make](#c-und-make-1)
Man müsste Zeile 95 in "CPP und Make" ändern
C++ wird zu C verarbeitet

2021-06-02 15:00 UTC, ZeroPointMax approved these changes

2021-06-02 15:00 UTC, ZeroPointMax commented on ASM-GUENTHER/README.md
> +- [C++ und Make](#c-und-make-1)
ahja, thx

2021-06-02 21:18 UTC, Steve2955 requested changes
Vielen Dank für die Mitschriften, habe nur einige Anmerkungen bezüglich der Formatierung gemacht

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +- Klar festlegen wann Aufgabe / Story Ready $\Rightarrow$ Doing und Doing $\Rightarrow$ Done geschoben werden kann
```suggestion
- Klar festlegen wann Aufgabe / Story Ready $\rightarrow$ Doing und Doing $\rightarrow$ Done geschoben werden kann
```

Können wir bei den kleinen Pfeilchen bleiben? 😅

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +- Dem Nutzer zeigen / mit ihm erstellen $\Rightarrow$ gewünschte Priorisierung wird klar
```suggestion
- Dem Nutzer zeigen / mit ihm erstellen $\rightarrow$ gewünschte Priorisierung wird klar
```

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +- Spaßfaktor $\Rightarrow$ Teamgeist
```suggestion
- Spaßfaktor $\rightarrow$ Teamgeist
```

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +- alle sind mit im Boot $\Rightarrow$ Engagement
```suggestion
- alle sind mit im Boot $\rightarrow$ Engagement
```

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +- anstatt Codezeilen zu schätzen $\Rightarrow$ Evaluierung von Eingangsgrößen von Funktionen
```suggestion
- anstatt Codezeilen zu schätzen $\rightarrow$ Evaluierung von Eingangsgrößen von Funktionen
```

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +weitere Präzisierung möglich
```suggestion
- "Constructive-Cost-Method"
- Lines-of-Code $=l$
- Mann-Monate $=MM$
- Entwicklungszeit $=t$
- Aufwandsanalyse $=t_{AA}$
- $t_{SW}=A(B\cdot (\frac{l}{1000})^{1+C})^{D}+t_{\text{Aufwandanalyse}}$
  - mit $A,B > 2, 0 < C,D < 1$
  - z.B. $t_{easySW}=2.5(2.4\cdot (\frac{l}{1000})^{1.05})^{0.38}+t_{AA}$
- für einfache, mittlere, komplexe SW-Projekte weitere Präzisierung möglich
```

Irgendwie hat hier die Formatierung etwas gefehlt 😅

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +  - Anzahl Datenelemente je Datenbestand einer Transaktion legt jeweils Wert S, M, L fest
```suggestion
- $FP_{roh}$ ermitteln
  - Werte gewichtet: $S, M, L$
  - Anzahl Datenelemente je Datenbestand einer Transaktion legt jeweils Wert $S, M, L$ fest
```

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +$Function Points = FP_{Roh}* Korrekturfaktoren$
```suggestion
$\text{Function Points} = FP_{roh}* \text{Korrekturfaktoren}$
```

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +  - $Anzahl_{MA}=\frac{FP}{150}$
```suggestion
  - $\text{Anzahl}_{MA}=\frac{FP}{150}$
```

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +- Starr, trocken, kein Teamgeist, keine Kommunikation
```suggestion
- starr, trocken, kein Teamgeist, keine Kommunikation
```

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +- ohne Maßzahlen von alten projekten **keine** zuverlässigen Aussage
```suggestion
- ohne Maßzahlen von alten Projekten **keine** zuverlässigen Aussage
```

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +  - mit gleichen und ähnlichen Projekten.
```suggestion
  - mit gleichen und ähnlichen Projekten
```

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +- präziser Entwurf nötig, Datenelemente, Transaktionen etc $\Rightarrow$ ändert sich oft während Entwicklung
```suggestion
- präziser Entwurf nötig $\rightarrow$ Datenelemente, Transaktionen usw. ändern sich oft während Entwicklung
```

Macht so für mich mehr Sinn

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +- $\frac{1}{Zeit}$
```suggestion
- $\frac{1}{\text{Kosten}}$
- $\frac{1}{\text{Zeit}}$
```

2021-06-02 21:18 UTC, Steve2955 commented on SWE-KASCHE/appendix/LKF.md
> +  **P**ausen-Karte (manchmal mit Kaffeetasse dargestellt): triviale Aufgabe oder: "Ich brauche eine Pause"
```suggestion
  **P**ausen-Karte (manchmal mit Kaffeetasse dargestellt): triviale Aufgabe oder: *"Ich brauche eine Pause"*
```

2021-06-03 08:30 UTC, nukerxy commented
Vielleicht machen wir es so, dass erst #72 gemerged wird, dann landen dessen Changes ja hier ?! ; Dann kann alles gleich in einem Rutsch auf Main.

2021-06-03 14:28 UTC, Steve2955 approved these changes

2021-06-03 14:28 UTC, merged